apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
  namespace: loh-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      nodeSelector:
        role: inventory # deploy to node with inventory label
      containers:
        - name: inventory
          image: fhuadeen/loh-inventory:prod
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 5001
          env:
            - name: INVENTORY_QUEUE
              value: "inventory"
            - name: AI_QUEUE
              value: "ai"
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: RABBITMQ_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: DATABASE_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: S3_BUCKET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-srv
  namespace: loh-apps
spec:
  selector:
    app: inventory
  ports:
    - name: inventory
      protocol: TCP
      port: 5001
      targetPort: 5001
